import Head from 'next/head';
import Link from 'next/link';

export default function About() {
    return (
        <div>
            <Head>
                <title>Daniel Pisati - About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>About</h1>
            <Link href="/">
                <a>click</a>
            </Link>
        </div>
    );
}
