import Head from 'next/head'
import Link from 'next/link'

import {projects} from '../../lib/data';

export default function Project(project) {
  return (
    <div>
      <Head>
        <title>Daniel Pisati - {project.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{project.title}</h1>
      <h1>{project.date}</h1>
      <p>{project.description}</p>
      <Link href="/"><a>click</a></Link>
    </div>
  )
}


export async function getStaticProps(context) {
    const { params } = context;
    const props = projects.find((item) => item.slug === params.slug);

    return {
        props
    }
}

export async function getStaticPaths() {
    const paths = projects.map((project) => ({
        params: {
            slug: project.slug,
        }
    }))

    return {
        paths,
        fallback: false
    }
}