import Head from 'next/head'
import Link from 'next/link'

import Header from '../../components/Header'
import Footer from '../../components/Footer'

import {projects} from '../../lib/data';
import ProjectPage from '../../components/ProjectPage';

export default function Project(project) {
  return (
    <div>
      <Head>
        <title>Daniel Pisati - {project.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isLandingPage={false} />
      <ProjectPage project={project} />
      <Footer isLandingPage={false} />
    </div>
  )
}


export async function getStaticProps(context) {
    const { params } = context;
    const props = projects.find((item) => item.slug === params.slug);

    return {
        props
    }
}

export async function getStaticPaths() {
    const paths = projects.map((project) => ({
        params: {
            slug: project.slug,
        }
    }))

    return {
        paths,
        fallback: false
    }
}